services:
  db:
    image: postgis/postgis:15-3.3
    container_name: hv_db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql:ro

  postgrest:
    image: postgrest/postgrest:latest
    container_name: hv_postgrest
    depends_on:
      - db
    ports:
      - "3000:3000"
    environment:
      PGRST_DB_URI: "postgres://postgres:postgres@db:5432/postgres"
      PGRST_DB_SCHEMA: "public"
      PGRST_DB_ANON_ROLE: "anon"
      PGRST_SERVER_HOST: "0.0.0.0"
      PGRST_SERVER_PORT: "3000"
